packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  esbuild: true
  sharp: true
overrides:
  drizzle-orm: "0.41.0"
peerDependencyRules:
  ignoreMissing:
    - gel
    - pg
    - postgres
    - "@opentelemetry/api"
